server:
  port: 8080
spring:
  datasource:
    username: root
    password: wang
    url: jdbc:mysql://localhost:3306/sakecloud?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: sakecloud
  servlet:
    multipart:
      # 单个文件的最大值
      max-file-size: 50MB
      # 上传文件的最大值
      max-request-size: 1000MB


mybatis:
  type-aliases-package: com.sake.sakecloud.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

file:
  path: D:/sakecloud
