server:
  port: 8080
spring:
  datasource:
    username: root
    password: wang
    url: jdbc:mysql://localhost:3306/sakecloud?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: sakecloud


mybatis:
  type-aliases-package: com.sake.sakecloud.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
